spring.application.name=courses
server.port=8081


# R2DBC PostgreSQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=admin
spring.r2dbc.driver=postgresql

